image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - echo     CI_REGISTRY_USER="$CI_REGISTRY_USER"  
  - echo CI_REGISTRY_PASSWORD="$CI_REGISTRY_PASSWORD" 
  - echo          CI_REGISTRY="$CI_REGISTRY" 
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER  --password-stdin $CI_REGISTRY

build:
  tags:
    - dind
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    refs:
      - v4